---
title: "About"
---

> Curious and passionate quantitative researcher with analytical thinking and project management skills.

Who am I?
-------------------------------

My professional background comes from nature sciences. I studied marine biology and ecology in my undergraduate (BSc) and specialised in fish community ecology in my masters (MSc).  
During my bachelor's degree I was exposed and started to engage with the world of data and became fascinated about it. At the time I had the opportunity to establish, maintain and analyse a sharks and rays observation database, and to set up a protocol for observations data collection and management, which is still in use by teams of marine biologists all around the Mediterranean.  
My two-year long master's was a great mix of survey dives (for other people's research) and data processing and analysis (for my research).  
Just before finishing my degree, I started working in an organisation that its main mission is to report the state of nature in Israel, and this is where I spent many days, months and, overall, about two years of data crunching, exploration and analysis to create insights on the processes that nature in Israel had gone through in the past 10-30 years. I worked with tabular data and with geographical data (combining R with QGIS and ArcGIS).  
I was also doing freelance work as an ecology specialist and data analyst for several clients including organisations, researchers, and councils.  


Scope 
-------------------------------
- Data management and cleaning
- Data analysis
- Data visualisation as an advocacy tool
- Capacity building, outreach and data literacy

I also like to paint horrible water-colour doodles, snorkel and dive, fail while trying to learn more stuff and to airdrum 🤟

:::: {.columns}

::: {.column width="60%"}

Skills
-------------------------------
-   **R language** and **RStudio** (aka *'posit'*)
-   **GIS**: ArcGIS and qGIS
-   **Github** repositories and collaboration (using **Git**)
-   Some experience with **SQL** queries
-   Basic knowledge coding in **Python** (using **pandas**, **matplotlib**...)
-   Website building with Quarto (like this one!), HTML and CSS.
-   **Science communication** via public speaking, scientific (reports) and non-scientific writing.

:::

::: {.column width="5%"}
<!-- empty column to create gap -->
:::


::: {.column width="35%"}
&nbsp;
&nbsp;
&nbsp;

<button class="button-28" role="button">[Browse my CV](https://raw.githubusercontent.com/shirasal/my_cv/main/shira_resume/shira_resume.pdf)</button>  

&nbsp;

See some of my work on my [GitHub profile](https://github.com/shirasal) or [here](https://linktr.ee/shirasal).

:::

::::